# Generated by Django 5.1.7 on 2025-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selectedColor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
