# Generated by Django 5.1.7 on 2025-04-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_selectedcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='selectedColor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
